# CMake generated Testfile for 
# Source directory: /mnt/c/Users/vande/Desktop/github/audited/loxguard
# Build directory: /mnt/c/Users/vande/Desktop/github/audited/loxguard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(loxguard_test "/mnt/c/Users/vande/Desktop/github/audited/loxguard/loxguard_test")
set_tests_properties(loxguard_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;429;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_backend_demo "/mnt/c/Users/vande/Desktop/github/audited/loxguard/loxguard_backend_demo")
set_tests_properties(loxguard_backend_demo PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;430;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_blackbox_layout_compat "/usr/bin/cmake" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/blackbox_layout_compat_check.cmake")
set_tests_properties(loxguard_blackbox_layout_compat PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;457;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_consumer_add_subdirectory "/usr/bin/cmake" "-DMODE=add_subdirectory" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard/consumer_add_subdirectory" "-DBUILD_TYPE=" "-DCONFIG=" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/consumer_smoke_test.cmake")
set_tests_properties(loxguard_consumer_add_subdirectory PROPERTIES  LABELS "consumer" _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;466;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_consumer_install_find_package "/usr/bin/cmake" "-DMODE=install_find_package" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard/consumer_install_find_package" "-DBUILD_TYPE=" "-DCONFIG=" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/consumer_smoke_test.cmake")
set_tests_properties(loxguard_consumer_install_find_package PROPERTIES  LABELS "consumer" _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;479;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_consumer_install_find_package_cpp "/usr/bin/cmake" "-DMODE=install_find_package_cpp" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard/consumer_install_find_package_cpp" "-DBUILD_TYPE=" "-DCONFIG=" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/consumer_smoke_test.cmake")
set_tests_properties(loxguard_consumer_install_find_package_cpp PROPERTIES  LABELS "consumer" _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;492;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_compile_fail_contracts "/usr/bin/cmake" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/compile_fail_contracts_check.cmake")
set_tests_properties(loxguard_compile_fail_contracts PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;505;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_version_consistency "/usr/bin/cmake" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DTAG=v1.0.0" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/version_consistency_check.cmake")
set_tests_properties(loxguard_version_consistency PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;514;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
add_test(loxguard_arm_compile_only "/usr/bin/cmake" "-DLOXGUARD_SOURCE_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-DARM_NONE_EABI_GCC=/usr/bin/arm-none-eabi-gcc" "-DWORK_DIR=/mnt/c/Users/vande/Desktop/github/audited/loxguard" "-P" "/mnt/c/Users/vande/Desktop/github/audited/loxguard/tools/arm_cortexm_compile_only.cmake")
set_tests_properties(loxguard_arm_compile_only PROPERTIES  _BACKTRACE_TRIPLES "/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;525;add_test;/mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeLists.txt;0;")
