# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/vande/Desktop/github/audited/loxguard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/vande/Desktop/github/audited/loxguard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeFiles /mnt/c/Users/vande/Desktop/github/audited/loxguard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/vande/Desktop/github/audited/loxguard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named loxguard

# Build rule for target.
loxguard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loxguard
.PHONY : loxguard

# fast build rule for target.
loxguard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/build
.PHONY : loxguard/fast

#=============================================================================
# Target rules for targets named loxguard_testlib

# Build rule for target.
loxguard_testlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loxguard_testlib
.PHONY : loxguard_testlib

# fast build rule for target.
loxguard_testlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/build
.PHONY : loxguard_testlib/fast

#=============================================================================
# Target rules for targets named loxguard_test

# Build rule for target.
loxguard_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loxguard_test
.PHONY : loxguard_test

# fast build rule for target.
loxguard_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/build
.PHONY : loxguard_test/fast

#=============================================================================
# Target rules for targets named loxguard_demo

# Build rule for target.
loxguard_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loxguard_demo
.PHONY : loxguard_demo

# fast build rule for target.
loxguard_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_demo.dir/build.make CMakeFiles/loxguard_demo.dir/build
.PHONY : loxguard_demo/fast

#=============================================================================
# Target rules for targets named loxguard_backend_demo

# Build rule for target.
loxguard_backend_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loxguard_backend_demo
.PHONY : loxguard_backend_demo

# fast build rule for target.
loxguard_backend_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_backend_demo.dir/build.make CMakeFiles/loxguard_backend_demo.dir/build
.PHONY : loxguard_backend_demo/fast

ecosystem/microhealth/src/mhealth.o: ecosystem/microhealth/src/mhealth.c.o
.PHONY : ecosystem/microhealth/src/mhealth.o

# target to build an object file
ecosystem/microhealth/src/mhealth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microhealth/src/mhealth.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microhealth/src/mhealth.c.o
.PHONY : ecosystem/microhealth/src/mhealth.c.o

ecosystem/microhealth/src/mhealth.i: ecosystem/microhealth/src/mhealth.c.i
.PHONY : ecosystem/microhealth/src/mhealth.i

# target to preprocess a source file
ecosystem/microhealth/src/mhealth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microhealth/src/mhealth.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microhealth/src/mhealth.c.i
.PHONY : ecosystem/microhealth/src/mhealth.c.i

ecosystem/microhealth/src/mhealth.s: ecosystem/microhealth/src/mhealth.c.s
.PHONY : ecosystem/microhealth/src/mhealth.s

# target to generate assembly for a file
ecosystem/microhealth/src/mhealth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microhealth/src/mhealth.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microhealth/src/mhealth.c.s
.PHONY : ecosystem/microhealth/src/mhealth.c.s

ecosystem/microlog/src/mlog.o: ecosystem/microlog/src/mlog.c.o
.PHONY : ecosystem/microlog/src/mlog.o

# target to build an object file
ecosystem/microlog/src/mlog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microlog/src/mlog.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microlog/src/mlog.c.o
.PHONY : ecosystem/microlog/src/mlog.c.o

ecosystem/microlog/src/mlog.i: ecosystem/microlog/src/mlog.c.i
.PHONY : ecosystem/microlog/src/mlog.i

# target to preprocess a source file
ecosystem/microlog/src/mlog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microlog/src/mlog.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microlog/src/mlog.c.i
.PHONY : ecosystem/microlog/src/mlog.c.i

ecosystem/microlog/src/mlog.s: ecosystem/microlog/src/mlog.c.s
.PHONY : ecosystem/microlog/src/mlog.s

# target to generate assembly for a file
ecosystem/microlog/src/mlog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/ecosystem/microlog/src/mlog.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/ecosystem/microlog/src/mlog.c.s
.PHONY : ecosystem/microlog/src/mlog.c.s

examples/guarded/guarded_parser.o: examples/guarded/guarded_parser.c.o
.PHONY : examples/guarded/guarded_parser.o

# target to build an object file
examples/guarded/guarded_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/examples/guarded/guarded_parser.c.o
.PHONY : examples/guarded/guarded_parser.c.o

examples/guarded/guarded_parser.i: examples/guarded/guarded_parser.c.i
.PHONY : examples/guarded/guarded_parser.i

# target to preprocess a source file
examples/guarded/guarded_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/examples/guarded/guarded_parser.c.i
.PHONY : examples/guarded/guarded_parser.c.i

examples/guarded/guarded_parser.s: examples/guarded/guarded_parser.c.s
.PHONY : examples/guarded/guarded_parser.s

# target to generate assembly for a file
examples/guarded/guarded_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/examples/guarded/guarded_parser.c.s
.PHONY : examples/guarded/guarded_parser.c.s

examples/host_backend_demo.o: examples/host_backend_demo.c.o
.PHONY : examples/host_backend_demo.o

# target to build an object file
examples/host_backend_demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_backend_demo.dir/build.make CMakeFiles/loxguard_backend_demo.dir/examples/host_backend_demo.c.o
.PHONY : examples/host_backend_demo.c.o

examples/host_backend_demo.i: examples/host_backend_demo.c.i
.PHONY : examples/host_backend_demo.i

# target to preprocess a source file
examples/host_backend_demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_backend_demo.dir/build.make CMakeFiles/loxguard_backend_demo.dir/examples/host_backend_demo.c.i
.PHONY : examples/host_backend_demo.c.i

examples/host_backend_demo.s: examples/host_backend_demo.c.s
.PHONY : examples/host_backend_demo.s

# target to generate assembly for a file
examples/host_backend_demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_backend_demo.dir/build.make CMakeFiles/loxguard_backend_demo.dir/examples/host_backend_demo.c.s
.PHONY : examples/host_backend_demo.c.s

examples/host_demo.o: examples/host_demo.c.o
.PHONY : examples/host_demo.o

# target to build an object file
examples/host_demo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_demo.dir/build.make CMakeFiles/loxguard_demo.dir/examples/host_demo.c.o
.PHONY : examples/host_demo.c.o

examples/host_demo.i: examples/host_demo.c.i
.PHONY : examples/host_demo.i

# target to preprocess a source file
examples/host_demo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_demo.dir/build.make CMakeFiles/loxguard_demo.dir/examples/host_demo.c.i
.PHONY : examples/host_demo.c.i

examples/host_demo.s: examples/host_demo.c.s
.PHONY : examples/host_demo.s

# target to generate assembly for a file
examples/host_demo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_demo.dir/build.make CMakeFiles/loxguard_demo.dir/examples/host_demo.c.s
.PHONY : examples/host_demo.c.s

src/adapters/loxguard_loxdb_adapter.o: src/adapters/loxguard_loxdb_adapter.c.o
.PHONY : src/adapters/loxguard_loxdb_adapter.o

# target to build an object file
src/adapters/loxguard_loxdb_adapter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_loxdb_adapter.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_loxdb_adapter.c.o
.PHONY : src/adapters/loxguard_loxdb_adapter.c.o

src/adapters/loxguard_loxdb_adapter.i: src/adapters/loxguard_loxdb_adapter.c.i
.PHONY : src/adapters/loxguard_loxdb_adapter.i

# target to preprocess a source file
src/adapters/loxguard_loxdb_adapter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_loxdb_adapter.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_loxdb_adapter.c.i
.PHONY : src/adapters/loxguard_loxdb_adapter.c.i

src/adapters/loxguard_loxdb_adapter.s: src/adapters/loxguard_loxdb_adapter.c.s
.PHONY : src/adapters/loxguard_loxdb_adapter.s

# target to generate assembly for a file
src/adapters/loxguard_loxdb_adapter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_loxdb_adapter.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_loxdb_adapter.c.s
.PHONY : src/adapters/loxguard_loxdb_adapter.c.s

src/adapters/loxguard_nvlog_adapter.o: src/adapters/loxguard_nvlog_adapter.c.o
.PHONY : src/adapters/loxguard_nvlog_adapter.o

# target to build an object file
src/adapters/loxguard_nvlog_adapter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_nvlog_adapter.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_nvlog_adapter.c.o
.PHONY : src/adapters/loxguard_nvlog_adapter.c.o

src/adapters/loxguard_nvlog_adapter.i: src/adapters/loxguard_nvlog_adapter.c.i
.PHONY : src/adapters/loxguard_nvlog_adapter.i

# target to preprocess a source file
src/adapters/loxguard_nvlog_adapter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_nvlog_adapter.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_nvlog_adapter.c.i
.PHONY : src/adapters/loxguard_nvlog_adapter.c.i

src/adapters/loxguard_nvlog_adapter.s: src/adapters/loxguard_nvlog_adapter.c.s
.PHONY : src/adapters/loxguard_nvlog_adapter.s

# target to generate assembly for a file
src/adapters/loxguard_nvlog_adapter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/adapters/loxguard_nvlog_adapter.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/adapters/loxguard_nvlog_adapter.c.s
.PHONY : src/adapters/loxguard_nvlog_adapter.c.s

src/loxguard.o: src/loxguard.c.o
.PHONY : src/loxguard.o

# target to build an object file
src/loxguard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard.c.o
.PHONY : src/loxguard.c.o

src/loxguard.i: src/loxguard.c.i
.PHONY : src/loxguard.i

# target to preprocess a source file
src/loxguard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard.c.i
.PHONY : src/loxguard.c.i

src/loxguard.s: src/loxguard.c.s
.PHONY : src/loxguard.s

# target to generate assembly for a file
src/loxguard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard.c.s
.PHONY : src/loxguard.c.s

src/loxguard_adapters.o: src/loxguard_adapters.c.o
.PHONY : src/loxguard_adapters.o

# target to build an object file
src/loxguard_adapters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_adapters.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_adapters.c.o
.PHONY : src/loxguard_adapters.c.o

src/loxguard_adapters.i: src/loxguard_adapters.c.i
.PHONY : src/loxguard_adapters.i

# target to preprocess a source file
src/loxguard_adapters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_adapters.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_adapters.c.i
.PHONY : src/loxguard_adapters.c.i

src/loxguard_adapters.s: src/loxguard_adapters.c.s
.PHONY : src/loxguard_adapters.s

# target to generate assembly for a file
src/loxguard_adapters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_adapters.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_adapters.c.s
.PHONY : src/loxguard_adapters.c.s

src/loxguard_backends.o: src/loxguard_backends.c.o
.PHONY : src/loxguard_backends.o

# target to build an object file
src/loxguard_backends.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_backends.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_backends.c.o
.PHONY : src/loxguard_backends.c.o

src/loxguard_backends.i: src/loxguard_backends.c.i
.PHONY : src/loxguard_backends.i

# target to preprocess a source file
src/loxguard_backends.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_backends.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_backends.c.i
.PHONY : src/loxguard_backends.c.i

src/loxguard_backends.s: src/loxguard_backends.c.s
.PHONY : src/loxguard_backends.s

# target to generate assembly for a file
src/loxguard_backends.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_backends.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_backends.c.s
.PHONY : src/loxguard_backends.c.s

src/loxguard_format.o: src/loxguard_format.c.o
.PHONY : src/loxguard_format.o

# target to build an object file
src/loxguard_format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_format.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_format.c.o
.PHONY : src/loxguard_format.c.o

src/loxguard_format.i: src/loxguard_format.c.i
.PHONY : src/loxguard_format.i

# target to preprocess a source file
src/loxguard_format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_format.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_format.c.i
.PHONY : src/loxguard_format.c.i

src/loxguard_format.s: src/loxguard_format.c.s
.PHONY : src/loxguard_format.s

# target to generate assembly for a file
src/loxguard_format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_format.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_format.c.s
.PHONY : src/loxguard_format.c.s

src/loxguard_ports.o: src/loxguard_ports.c.o
.PHONY : src/loxguard_ports.o

# target to build an object file
src/loxguard_ports.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_ports.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_ports.c.o
.PHONY : src/loxguard_ports.c.o

src/loxguard_ports.i: src/loxguard_ports.c.i
.PHONY : src/loxguard_ports.i

# target to preprocess a source file
src/loxguard_ports.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_ports.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_ports.c.i
.PHONY : src/loxguard_ports.c.i

src/loxguard_ports.s: src/loxguard_ports.c.s
.PHONY : src/loxguard_ports.s

# target to generate assembly for a file
src/loxguard_ports.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_ports.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_ports.c.s
.PHONY : src/loxguard_ports.c.s

src/loxguard_rtos_bridge.o: src/loxguard_rtos_bridge.c.o
.PHONY : src/loxguard_rtos_bridge.o

# target to build an object file
src/loxguard_rtos_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_rtos_bridge.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_rtos_bridge.c.o
.PHONY : src/loxguard_rtos_bridge.c.o

src/loxguard_rtos_bridge.i: src/loxguard_rtos_bridge.c.i
.PHONY : src/loxguard_rtos_bridge.i

# target to preprocess a source file
src/loxguard_rtos_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_rtos_bridge.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_rtos_bridge.c.i
.PHONY : src/loxguard_rtos_bridge.c.i

src/loxguard_rtos_bridge.s: src/loxguard_rtos_bridge.c.s
.PHONY : src/loxguard_rtos_bridge.s

# target to generate assembly for a file
src/loxguard_rtos_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_rtos_bridge.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_rtos_bridge.c.s
.PHONY : src/loxguard_rtos_bridge.c.s

src/loxguard_shell.o: src/loxguard_shell.c.o
.PHONY : src/loxguard_shell.o

# target to build an object file
src/loxguard_shell.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_shell.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_shell.c.o
.PHONY : src/loxguard_shell.c.o

src/loxguard_shell.i: src/loxguard_shell.c.i
.PHONY : src/loxguard_shell.i

# target to preprocess a source file
src/loxguard_shell.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_shell.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_shell.c.i
.PHONY : src/loxguard_shell.c.i

src/loxguard_shell.s: src/loxguard_shell.c.s
.PHONY : src/loxguard_shell.s

# target to generate assembly for a file
src/loxguard_shell.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard.dir/build.make CMakeFiles/loxguard.dir/src/loxguard_shell.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_testlib.dir/build.make CMakeFiles/loxguard_testlib.dir/src/loxguard_shell.c.s
.PHONY : src/loxguard_shell.c.s

tests/test_arena.o: tests/test_arena.c.o
.PHONY : tests/test_arena.o

# target to build an object file
tests/test_arena.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_arena.c.o
.PHONY : tests/test_arena.c.o

tests/test_arena.i: tests/test_arena.c.i
.PHONY : tests/test_arena.i

# target to preprocess a source file
tests/test_arena.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_arena.c.i
.PHONY : tests/test_arena.c.i

tests/test_arena.s: tests/test_arena.c.s
.PHONY : tests/test_arena.s

# target to generate assembly for a file
tests/test_arena.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_arena.c.s
.PHONY : tests/test_arena.c.s

tests/test_common.o: tests/test_common.c.o
.PHONY : tests/test_common.o

# target to build an object file
tests/test_common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_common.c.o
.PHONY : tests/test_common.c.o

tests/test_common.i: tests/test_common.c.i
.PHONY : tests/test_common.i

# target to preprocess a source file
tests/test_common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_common.c.i
.PHONY : tests/test_common.c.i

tests/test_common.s: tests/test_common.c.s
.PHONY : tests/test_common.s

# target to generate assembly for a file
tests/test_common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_common.c.s
.PHONY : tests/test_common.c.s

tests/test_guarded_module.o: tests/test_guarded_module.c.o
.PHONY : tests/test_guarded_module.o

# target to build an object file
tests/test_guarded_module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_guarded_module.c.o
.PHONY : tests/test_guarded_module.c.o

tests/test_guarded_module.i: tests/test_guarded_module.c.i
.PHONY : tests/test_guarded_module.i

# target to preprocess a source file
tests/test_guarded_module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_guarded_module.c.i
.PHONY : tests/test_guarded_module.c.i

tests/test_guarded_module.s: tests/test_guarded_module.c.s
.PHONY : tests/test_guarded_module.s

# target to generate assembly for a file
tests/test_guarded_module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_guarded_module.c.s
.PHONY : tests/test_guarded_module.c.s

tests/test_loxguard_run.o: tests/test_loxguard_run.c.o
.PHONY : tests/test_loxguard_run.o

# target to build an object file
tests/test_loxguard_run.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_loxguard_run.c.o
.PHONY : tests/test_loxguard_run.c.o

tests/test_loxguard_run.i: tests/test_loxguard_run.c.i
.PHONY : tests/test_loxguard_run.i

# target to preprocess a source file
tests/test_loxguard_run.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_loxguard_run.c.i
.PHONY : tests/test_loxguard_run.c.i

tests/test_loxguard_run.s: tests/test_loxguard_run.c.s
.PHONY : tests/test_loxguard_run.s

# target to generate assembly for a file
tests/test_loxguard_run.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_loxguard_run.c.s
.PHONY : tests/test_loxguard_run.c.s

tests/test_main.o: tests/test_main.c.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_main.c.o
.PHONY : tests/test_main.c.o

tests/test_main.i: tests/test_main.c.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_main.c.i
.PHONY : tests/test_main.c.i

tests/test_main.s: tests/test_main.c.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_main.c.s
.PHONY : tests/test_main.c.s

tests/test_phase01_core.o: tests/test_phase01_core.c.o
.PHONY : tests/test_phase01_core.o

# target to build an object file
tests/test_phase01_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_phase01_core.c.o
.PHONY : tests/test_phase01_core.c.o

tests/test_phase01_core.i: tests/test_phase01_core.c.i
.PHONY : tests/test_phase01_core.i

# target to preprocess a source file
tests/test_phase01_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_phase01_core.c.i
.PHONY : tests/test_phase01_core.c.i

tests/test_phase01_core.s: tests/test_phase01_core.c.s
.PHONY : tests/test_phase01_core.s

# target to generate assembly for a file
tests/test_phase01_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_phase01_core.c.s
.PHONY : tests/test_phase01_core.c.s

tests/test_pipeline.o: tests/test_pipeline.c.o
.PHONY : tests/test_pipeline.o

# target to build an object file
tests/test_pipeline.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline.c.o
.PHONY : tests/test_pipeline.c.o

tests/test_pipeline.i: tests/test_pipeline.c.i
.PHONY : tests/test_pipeline.i

# target to preprocess a source file
tests/test_pipeline.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline.c.i
.PHONY : tests/test_pipeline.c.i

tests/test_pipeline.s: tests/test_pipeline.c.s
.PHONY : tests/test_pipeline.s

# target to generate assembly for a file
tests/test_pipeline.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline.c.s
.PHONY : tests/test_pipeline.c.s

tests/test_pipeline_legacy.o: tests/test_pipeline_legacy.c.o
.PHONY : tests/test_pipeline_legacy.o

# target to build an object file
tests/test_pipeline_legacy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline_legacy.c.o
.PHONY : tests/test_pipeline_legacy.c.o

tests/test_pipeline_legacy.i: tests/test_pipeline_legacy.c.i
.PHONY : tests/test_pipeline_legacy.i

# target to preprocess a source file
tests/test_pipeline_legacy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline_legacy.c.i
.PHONY : tests/test_pipeline_legacy.c.i

tests/test_pipeline_legacy.s: tests/test_pipeline_legacy.c.s
.PHONY : tests/test_pipeline_legacy.s

# target to generate assembly for a file
tests/test_pipeline_legacy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_pipeline_legacy.c.s
.PHONY : tests/test_pipeline_legacy.c.s

tests/test_ports.o: tests/test_ports.c.o
.PHONY : tests/test_ports.o

# target to build an object file
tests/test_ports.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_ports.c.o
.PHONY : tests/test_ports.c.o

tests/test_ports.i: tests/test_ports.c.i
.PHONY : tests/test_ports.i

# target to preprocess a source file
tests/test_ports.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_ports.c.i
.PHONY : tests/test_ports.c.i

tests/test_ports.s: tests/test_ports.c.s
.PHONY : tests/test_ports.s

# target to generate assembly for a file
tests/test_ports.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_ports.c.s
.PHONY : tests/test_ports.c.s

tests/test_rtos_bridge.o: tests/test_rtos_bridge.c.o
.PHONY : tests/test_rtos_bridge.o

# target to build an object file
tests/test_rtos_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_rtos_bridge.c.o
.PHONY : tests/test_rtos_bridge.c.o

tests/test_rtos_bridge.i: tests/test_rtos_bridge.c.i
.PHONY : tests/test_rtos_bridge.i

# target to preprocess a source file
tests/test_rtos_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_rtos_bridge.c.i
.PHONY : tests/test_rtos_bridge.c.i

tests/test_rtos_bridge.s: tests/test_rtos_bridge.c.s
.PHONY : tests/test_rtos_bridge.s

# target to generate assembly for a file
tests/test_rtos_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_rtos_bridge.c.s
.PHONY : tests/test_rtos_bridge.c.s

tests/test_shell.o: tests/test_shell.c.o
.PHONY : tests/test_shell.o

# target to build an object file
tests/test_shell.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_shell.c.o
.PHONY : tests/test_shell.c.o

tests/test_shell.i: tests/test_shell.c.i
.PHONY : tests/test_shell.i

# target to preprocess a source file
tests/test_shell.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_shell.c.i
.PHONY : tests/test_shell.c.i

tests/test_shell.s: tests/test_shell.c.s
.PHONY : tests/test_shell.s

# target to generate assembly for a file
tests/test_shell.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_shell.c.s
.PHONY : tests/test_shell.c.s

tests/test_span.o: tests/test_span.c.o
.PHONY : tests/test_span.o

# target to build an object file
tests/test_span.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_span.c.o
.PHONY : tests/test_span.c.o

tests/test_span.i: tests/test_span.c.i
.PHONY : tests/test_span.i

# target to preprocess a source file
tests/test_span.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_span.c.i
.PHONY : tests/test_span.c.i

tests/test_span.s: tests/test_span.c.s
.PHONY : tests/test_span.s

# target to generate assembly for a file
tests/test_span.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loxguard_test.dir/build.make CMakeFiles/loxguard_test.dir/tests/test_span.c.s
.PHONY : tests/test_span.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... loxguard"
	@echo "... loxguard_backend_demo"
	@echo "... loxguard_demo"
	@echo "... loxguard_test"
	@echo "... loxguard_testlib"
	@echo "... ecosystem/microhealth/src/mhealth.o"
	@echo "... ecosystem/microhealth/src/mhealth.i"
	@echo "... ecosystem/microhealth/src/mhealth.s"
	@echo "... ecosystem/microlog/src/mlog.o"
	@echo "... ecosystem/microlog/src/mlog.i"
	@echo "... ecosystem/microlog/src/mlog.s"
	@echo "... examples/guarded/guarded_parser.o"
	@echo "... examples/guarded/guarded_parser.i"
	@echo "... examples/guarded/guarded_parser.s"
	@echo "... examples/host_backend_demo.o"
	@echo "... examples/host_backend_demo.i"
	@echo "... examples/host_backend_demo.s"
	@echo "... examples/host_demo.o"
	@echo "... examples/host_demo.i"
	@echo "... examples/host_demo.s"
	@echo "... src/adapters/loxguard_loxdb_adapter.o"
	@echo "... src/adapters/loxguard_loxdb_adapter.i"
	@echo "... src/adapters/loxguard_loxdb_adapter.s"
	@echo "... src/adapters/loxguard_nvlog_adapter.o"
	@echo "... src/adapters/loxguard_nvlog_adapter.i"
	@echo "... src/adapters/loxguard_nvlog_adapter.s"
	@echo "... src/loxguard.o"
	@echo "... src/loxguard.i"
	@echo "... src/loxguard.s"
	@echo "... src/loxguard_adapters.o"
	@echo "... src/loxguard_adapters.i"
	@echo "... src/loxguard_adapters.s"
	@echo "... src/loxguard_backends.o"
	@echo "... src/loxguard_backends.i"
	@echo "... src/loxguard_backends.s"
	@echo "... src/loxguard_format.o"
	@echo "... src/loxguard_format.i"
	@echo "... src/loxguard_format.s"
	@echo "... src/loxguard_ports.o"
	@echo "... src/loxguard_ports.i"
	@echo "... src/loxguard_ports.s"
	@echo "... src/loxguard_rtos_bridge.o"
	@echo "... src/loxguard_rtos_bridge.i"
	@echo "... src/loxguard_rtos_bridge.s"
	@echo "... src/loxguard_shell.o"
	@echo "... src/loxguard_shell.i"
	@echo "... src/loxguard_shell.s"
	@echo "... tests/test_arena.o"
	@echo "... tests/test_arena.i"
	@echo "... tests/test_arena.s"
	@echo "... tests/test_common.o"
	@echo "... tests/test_common.i"
	@echo "... tests/test_common.s"
	@echo "... tests/test_guarded_module.o"
	@echo "... tests/test_guarded_module.i"
	@echo "... tests/test_guarded_module.s"
	@echo "... tests/test_loxguard_run.o"
	@echo "... tests/test_loxguard_run.i"
	@echo "... tests/test_loxguard_run.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
	@echo "... tests/test_phase01_core.o"
	@echo "... tests/test_phase01_core.i"
	@echo "... tests/test_phase01_core.s"
	@echo "... tests/test_pipeline.o"
	@echo "... tests/test_pipeline.i"
	@echo "... tests/test_pipeline.s"
	@echo "... tests/test_pipeline_legacy.o"
	@echo "... tests/test_pipeline_legacy.i"
	@echo "... tests/test_pipeline_legacy.s"
	@echo "... tests/test_ports.o"
	@echo "... tests/test_ports.i"
	@echo "... tests/test_ports.s"
	@echo "... tests/test_rtos_bridge.o"
	@echo "... tests/test_rtos_bridge.i"
	@echo "... tests/test_rtos_bridge.s"
	@echo "... tests/test_shell.o"
	@echo "... tests/test_shell.i"
	@echo "... tests/test_shell.s"
	@echo "... tests/test_span.o"
	@echo "... tests/test_span.i"
	@echo "... tests/test_span.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

