# CMake generated Testfile for 
# Source directory: C:/Users/vande/Desktop/loxguard
# Build directory: C:/Users/vande/Desktop/loxguard/build_nvlog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(loxguard_test "C:/Users/vande/Desktop/loxguard/build_nvlog/Debug/loxguard_test.exe")
  set_tests_properties(loxguard_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;90;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(loxguard_test "C:/Users/vande/Desktop/loxguard/build_nvlog/Release/loxguard_test.exe")
  set_tests_properties(loxguard_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;90;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(loxguard_test "C:/Users/vande/Desktop/loxguard/build_nvlog/MinSizeRel/loxguard_test.exe")
  set_tests_properties(loxguard_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;90;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(loxguard_test "C:/Users/vande/Desktop/loxguard/build_nvlog/RelWithDebInfo/loxguard_test.exe")
  set_tests_properties(loxguard_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;90;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
else()
  add_test(loxguard_test NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(loxguard_backend_demo "C:/Users/vande/Desktop/loxguard/build_nvlog/Debug/loxguard_backend_demo.exe")
  set_tests_properties(loxguard_backend_demo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;91;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(loxguard_backend_demo "C:/Users/vande/Desktop/loxguard/build_nvlog/Release/loxguard_backend_demo.exe")
  set_tests_properties(loxguard_backend_demo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;91;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(loxguard_backend_demo "C:/Users/vande/Desktop/loxguard/build_nvlog/MinSizeRel/loxguard_backend_demo.exe")
  set_tests_properties(loxguard_backend_demo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;91;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(loxguard_backend_demo "C:/Users/vande/Desktop/loxguard/build_nvlog/RelWithDebInfo/loxguard_backend_demo.exe")
  set_tests_properties(loxguard_backend_demo PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;91;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
else()
  add_test(loxguard_backend_demo NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(loxguard_static_check "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/src")
  set_tests_properties(loxguard_static_check PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;92;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(loxguard_static_check "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/src")
  set_tests_properties(loxguard_static_check PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;92;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(loxguard_static_check "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/src")
  set_tests_properties(loxguard_static_check PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;92;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(loxguard_static_check "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/src")
  set_tests_properties(loxguard_static_check PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;92;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
else()
  add_test(loxguard_static_check NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(loxguard_static_check_guarded "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/examples/guarded")
  set_tests_properties(loxguard_static_check_guarded PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;96;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(loxguard_static_check_guarded "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/examples/guarded")
  set_tests_properties(loxguard_static_check_guarded PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;96;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(loxguard_static_check_guarded "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/examples/guarded")
  set_tests_properties(loxguard_static_check_guarded PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;96;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(loxguard_static_check_guarded "powershell" "-ExecutionPolicy" "Bypass" "-File" "C:/Users/vande/Desktop/loxguard/tools/guard_static_check.ps1" "-Path" "C:/Users/vande/Desktop/loxguard/examples/guarded")
  set_tests_properties(loxguard_static_check_guarded PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/vande/Desktop/loxguard/CMakeLists.txt;96;add_test;C:/Users/vande/Desktop/loxguard/CMakeLists.txt;0;")
else()
  add_test(loxguard_static_check_guarded NOT_AVAILABLE)
endif()
