cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED MODE)
    message(FATAL_ERROR "MODE is required (add_subdirectory|install_find_package).")
endif()
if(NOT DEFINED LOXGUARD_SOURCE_DIR)
    message(FATAL_ERROR "LOXGUARD_SOURCE_DIR is required.")
endif()
if(NOT DEFINED WORK_DIR)
    message(FATAL_ERROR "WORK_DIR is required.")
endif()

set(_build_type "")
if(DEFINED BUILD_TYPE AND NOT BUILD_TYPE STREQUAL "")
    set(_build_type "${BUILD_TYPE}")
endif()

set(_config "")
if(DEFINED CONFIG AND NOT CONFIG STREQUAL "")
    set(_config "${CONFIG}")
endif()

function(_run)
    execute_process(
        COMMAND ${ARGV}
        RESULT_VARIABLE _rv
    )
    if(NOT _rv EQUAL 0)
        message(FATAL_ERROR "Command failed (${_rv}): ${ARGV}")
    endif()
endfunction()

set(_work "${WORK_DIR}")
file(MAKE_DIRECTORY "${_work}")

if(MODE STREQUAL "add_subdirectory")
    set(_src "${LOXGUARD_SOURCE_DIR}/tests/consumer/add_subdirectory")
    set(_bld "${_work}/build_add_subdirectory")
    _run(${CMAKE_COMMAND} -E rm -rf "${_bld}")
    if(_build_type STREQUAL "")
        _run(${CMAKE_COMMAND} -S "${_src}" -B "${_bld}")
    else()
        _run(${CMAKE_COMMAND} -S "${_src}" -B "${_bld}" "-DCMAKE_BUILD_TYPE=${_build_type}")
    endif()
    if(_config STREQUAL "")
        _run(${CMAKE_COMMAND} --build "${_bld}")
        _run(${CMAKE_CTEST_COMMAND} --test-dir "${_bld}" --output-on-failure)
    else()
        _run(${CMAKE_COMMAND} --build "${_bld}" --config "${_config}")
        _run(${CMAKE_CTEST_COMMAND} --test-dir "${_bld}" -C "${_config}" --output-on-failure)
    endif()
    return()
endif()

if(MODE STREQUAL "install_find_package")
    set(_prefix "${_work}/install_prefix")
    set(_bld_install "${_work}/build_install")
    set(_bld_consumer "${_work}/build_consumer")
    set(_consumer_src "${LOXGUARD_SOURCE_DIR}/tests/consumer/install_find_package")

    _run(${CMAKE_COMMAND} -E rm -rf "${_prefix}")
    _run(${CMAKE_COMMAND} -E rm -rf "${_bld_install}")
    _run(${CMAKE_COMMAND} -E rm -rf "${_bld_consumer}")

    if(_build_type STREQUAL "")
        _run(${CMAKE_COMMAND} -S "${LOXGUARD_SOURCE_DIR}" -B "${_bld_install}" -DLOXGUARD_BUILD_TESTS=OFF)
    else()
        _run(${CMAKE_COMMAND} -S "${LOXGUARD_SOURCE_DIR}" -B "${_bld_install}" -DLOXGUARD_BUILD_TESTS=OFF "-DCMAKE_BUILD_TYPE=${_build_type}")
    endif()
    if(_config STREQUAL "")
        _run(${CMAKE_COMMAND} --build "${_bld_install}")
        _run(${CMAKE_COMMAND} --install "${_bld_install}" --prefix "${_prefix}")
    else()
        _run(${CMAKE_COMMAND} --build "${_bld_install}" --config "${_config}")
        _run(${CMAKE_COMMAND} --install "${_bld_install}" --prefix "${_prefix}" --config "${_config}")
    endif()

    if(_build_type STREQUAL "")
        _run(${CMAKE_COMMAND} -S "${_consumer_src}" -B "${_bld_consumer}" "-DCMAKE_PREFIX_PATH=${_prefix}")
    else()
        _run(${CMAKE_COMMAND} -S "${_consumer_src}" -B "${_bld_consumer}" "-DCMAKE_PREFIX_PATH=${_prefix}" "-DCMAKE_BUILD_TYPE=${_build_type}")
    endif()
    if(_config STREQUAL "")
        _run(${CMAKE_COMMAND} --build "${_bld_consumer}")
        _run(${CMAKE_CTEST_COMMAND} --test-dir "${_bld_consumer}" --output-on-failure)
    else()
        _run(${CMAKE_COMMAND} --build "${_bld_consumer}" --config "${_config}")
        _run(${CMAKE_CTEST_COMMAND} --test-dir "${_bld_consumer}" -C "${_config}" --output-on-failure)
    endif()
    return()
endif()

message(FATAL_ERROR "Unknown MODE='${MODE}'.")
