cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED LOXGUARD_SOURCE_DIR)
    message(FATAL_ERROR "LOXGUARD_SOURCE_DIR is required.")
endif()
if(NOT DEFINED TAG)
    message(FATAL_ERROR "TAG is required.")
endif()

file(TO_CMAKE_PATH "${LOXGUARD_SOURCE_DIR}" _src)

file(READ "${_src}/CMakeLists.txt" _cmake_lists)
string(REGEX MATCH "project\\(loxguard VERSION ([0-9]+\\.[0-9]+\\.[0-9]+) LANGUAGES C\\)" _cmake_match "${_cmake_lists}")
if(NOT _cmake_match)
    message(FATAL_ERROR "Could not read project version from CMakeLists.txt")
endif()
set(_project_version "${CMAKE_MATCH_1}")

file(READ "${_src}/include/loxguard.h" _header)
foreach(_name MAJOR MINOR PATCH)
    string(REGEX MATCH "#define LOXGUARD_VERSION_${_name} ([0-9]+)" _match "${_header}")
    if(NOT _match)
        message(FATAL_ERROR "Missing LOXGUARD_VERSION_${_name} in include/loxguard.h")
    endif()
    set("_header_${_name}" "${CMAKE_MATCH_1}")
endforeach()
set(_header_version "${_header_MAJOR}.${_header_MINOR}.${_header_PATCH}")

if(NOT "${TAG}" MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "Tag '${TAG}' is not a semantic version tag")
endif()

set(_tag_version "${TAG}")
string(REGEX REPLACE "^v" "" _tag_version "${_tag_version}")

if(NOT _tag_version STREQUAL _project_version)
    message(FATAL_ERROR "Tag version ${_tag_version} does not match CMake project version ${_project_version}")
endif()

if(NOT _tag_version STREQUAL _header_version)
    message(FATAL_ERROR "Tag version ${_tag_version} does not match public header version ${_header_version}")
endif()

if(NOT EXISTS "${_src}/CHANGELOG.md")
    message(FATAL_ERROR "CHANGELOG.md is missing")
endif()
file(READ "${_src}/CHANGELOG.md" _changelog)
if(_changelog MATCHES "## v${_tag_version} \\(")
else()
    message(FATAL_ERROR "CHANGELOG.md does not contain an entry for v${_tag_version}")
endif()

set(_release_notes "${_src}/docs/RELEASE_NOTES_v${_tag_version}.md")
if(NOT EXISTS "${_release_notes}")
    message(FATAL_ERROR "Release notes file is missing: ${_release_notes}")
endif()
file(READ "${_release_notes}" _notes)
if(NOT _notes MATCHES "v${_tag_version}")
    message(FATAL_ERROR "Release notes file does not reference v${_tag_version}")
endif()
